# Generated by Django 5.1.1 on 2024-10-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_job_area_remove_job_cost_alter_job_name_and_more'),
        ('shots', '0025_alter_package_package_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot',
            name='job',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='md',
        ),
        migrations.AddField(
            model_name='shot',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='clients.area'),
        ),
        migrations.AddField(
            model_name='shot',
            name='md_comp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='md_paint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='md_roto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='md_track',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
