# Generated by Django 5.1.1 on 2024-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0026_remove_shot_job_remove_shot_md_shot_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='go',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shot',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
