# Generated by Django 5.1.1 on 2024-10-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_area_alter_job_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
    ]
