# Generated by Django 5.1.1 on 2024-10-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_job_area_remove_job_cost_alter_job_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.AddField(
            model_name='job',
            name='name_job',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
